/**
 * AUTO-GENERATED DOCUMENTATION
 * 
 * This file is automatically generated from source code.
 * DO NOT EDIT MANUALLY - Changes will be overwritten!
 * 
 * Generated: 2026-02-23T18:49:30.850Z
 * Run: pnpm extract-docs to regenerate
 */

export interface CodeExample {
  id: string
  title: string
  description: string
  language: string
  code: string
  source: string
  lastUpdated: string
}

export interface TypeDefinition {
  name: string
  definition: string
  description: string
  source: string
}

export interface APIEndpoint {
  method: string
  path: string
  description: string
  requestBody?: string
  responseBody?: string
  headers?: string[]
  source: string
}

export interface EnvVariable {
  key: string
  defaultValue?: string
  description: string
  required: boolean
  source: string
}

export const generatedCodeExamples: CodeExample[] = [
  {
    "id": "facilitator-env-alpha",
    "title": "Facilitator Configuration (ALPHA)",
    "description": "Environment configuration for facilitator with auto-registration",
    "language": "bash",
    "code": "# Alpha Facilitator Configuration\nPORT=4000\n\n# Network Configuration\nRPC_URL_TESTNET=https://rpc.testnet.x1.xyz\nRPC_URL_MAINNET=https://rpc.mainnet.x1.xyz\nNETWORK=x1-testnet\n\n# Token Configuration\nWXNT_MINT=So11111111111111111111111111111111111111112\nUSDX_MINT=B69chRzqzDCmdB5WYB8NRu5Yv5ZA95ABiZcdzCgGm9Tq\n\n# Facilitator Identity\nFACILITATOR_ID=alpha\nFACILITATOR_NAME=\"Alpha Facilitator\"\n\n# Fee Configuration (basis points, e.g., 10 = 0.1%)\nFEE_BASIS_POINTS=10\n\n# Wallet Configuration - FUNDED WALLET\n# Address: J7s6Lsg6oY1g1Xj2VCRgu1kZ8JjZyMudCrEminPJRCec\n# Balance: ~2.6 XNT\nFEE_PAYER_SECRET=your-fee-payer-secret-key-here\n\n# Stats Reset Password (for development)\nSTATS_RESET_PASSWORD=dev-reset-2024\n",
    "source": "packages/facilitator/.env.alpha",
    "lastUpdated": "2026-02-23T18:49:30.849Z"
  },
  {
    "id": "facilitator-auto-register",
    "title": "Facilitator Auto-Registration",
    "description": "Automatically register facilitator with API on startup",
    "language": "typescript",
    "code": "// Auto-registration happens automatically when facilitator starts\n// Configuration from environment variables:\nexport async function initializeFacilitator(\n  config: RegistrationConfig,\n  getStats: () => HeartbeatStats\n): Promise<boolean> {\n  // Step 1: Register with API\n  const registered = await registerFacilitator(config);\n  \n  if (!registered) {\n    logger.error('Failed to register facilitator - heartbeat will not start');\n    return false;\n  }\n\n  // Step 2: Start heartbeat\n  startHeartbeat(config.facilitatorId, config.apiUrl, getStats);\n\n  logger.info({\n    id: config.facilitatorId,\n    name: config.facilitatorName\n  }, '✅ Facilitator initialization complete');\n\n  return true;\n}",
    "source": "packages/facilitator/src/lib/registry.ts",
    "lastUpdated": "2026-02-23T18:49:30.849Z"
  }
]

export const generatedTypeDefinitions: TypeDefinition[] = [
  {
    "name": "FacilitatorInfo",
    "definition": "export interface FacilitatorInfo {\n  id: string;\n  name: string;\n  url: string;\n  fee: number; // Basis points (e.g., 10 = 0.1%)\n  status: 'active' | 'inactive';\n  network: 'x1-testnet' | 'x1-mainnet';\n  address?: string;\n  stats?: {\n    uptime?: number;\n    successRate?: number;\n    avgResponseTime?: number;\n    totalSettlements?: number;\n  };\n}",
    "description": "Information about a registered facilitator",
    "source": "packages/client/src/facilitatorDiscovery.ts"
  },
  {
    "name": "FacilitatorSelectionOptions",
    "definition": "export interface FacilitatorSelectionOptions {\n  network?: 'x1-testnet' | 'x1-mainnet';\n  maxFee?: number; // Maximum fee in basis points\n  minSuccessRate?: number; // Minimum success rate (0-100)\n  minUptime?: number; // Minimum uptime in seconds\n  preferredIds?: string[]; // Preferred facilitator IDs\n  sortBy?: 'fee' | 'successRate' | 'uptime' | 'random';\n}",
    "description": "Options for selecting the best facilitator",
    "source": "packages/client/src/facilitatorDiscovery.ts"
  }
]

export const generatedAPIEndpoints: APIEndpoint[] = [
  {
    "method": "POST",
    "path": "/facilitators/register",
    "description": "Register a new facilitator with the API registry",
    "requestBody": "{\n  \"id\": \"alpha\",\n  \"name\": \"Alpha Facilitator\",\n  \"address\": \"FACILITATOR_WALLET_ADDRESS\",\n  \"url\": \"http://localhost:4000\",\n  \"feeBasisPoints\": 10,\n  \"network\": \"x1-testnet\"\n}",
    "responseBody": "{\n  \"message\": \"Facilitator registered successfully\",\n  \"facilitator\": {\n    \"id\": \"alpha\",\n    \"status\": \"active\",\n    \"lastHeartbeat\": \"2025-11-06T13:00:00.000Z\"\n  }\n}",
    "headers": [
      "Content-Type: application/json"
    ],
    "source": "packages/api/src/routes/facilitators.ts"
  },
  {
    "method": "POST",
    "path": "/facilitators/heartbeat",
    "description": "Send heartbeat to maintain active status",
    "requestBody": "{\n  \"id\": \"alpha\",\n  \"stats\": {\n    \"uptime\": 99.9,\n    \"successRate\": 100,\n    \"avgResponseTime\": 42,\n    \"totalSettlements\": 1337\n  }\n}",
    "responseBody": "{\n  \"message\": \"Heartbeat received\",\n  \"status\": \"active\"\n}",
    "headers": [
      "Content-Type: application/json"
    ],
    "source": "packages/api/src/routes/facilitators.ts"
  },
  {
    "method": "GET",
    "path": "/facilitators?network=x1-testnet&health=true",
    "description": "List all registered facilitators with health checks",
    "responseBody": "{\n  \"facilitators\": [\n    {\n      \"id\": \"alpha\",\n      \"name\": \"Alpha Facilitator\",\n      \"status\": \"active\",\n      \"health\": {\n        \"status\": \"healthy\",\n        \"uptime\": 99.9\n      }\n    }\n  ],\n  \"network\": \"x1-testnet\",\n  \"total\": 3,\n  \"active\": 2\n}",
    "source": "packages/api/src/routes/facilitators.ts"
  }
]

export const generatedEnvVariables: EnvVariable[] = [
  {
    "key": "PORT",
    "defaultValue": "4000",
    "description": "Port number for the facilitator service",
    "required": true,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "RPC_URL_TESTNET",
    "defaultValue": "https://rpc.testnet.x1.xyz",
    "description": "X1 testnet RPC endpoint",
    "required": false,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "RPC_URL_MAINNET",
    "defaultValue": "https://rpc.mainnet.x1.xyz",
    "description": "X1 mainnet RPC endpoint",
    "required": false,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "NETWORK",
    "defaultValue": "x1-testnet",
    "description": "Blockchain network (x1-testnet or x1-mainnet)",
    "required": true,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "WXNT_MINT",
    "defaultValue": "So11111111111111111111111111111111111111112",
    "description": "Configuration variable",
    "required": false,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "USDX_MINT",
    "defaultValue": "B69chRzqzDCmdB5WYB8NRu5Yv5ZA95ABiZcdzCgGm9Tq",
    "description": "Configuration variable",
    "required": false,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "FACILITATOR_ID",
    "defaultValue": "alpha",
    "description": "Unique identifier for this facilitator",
    "required": true,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "FACILITATOR_NAME",
    "defaultValue": "\"Alpha Facilitator\"",
    "description": "Human-readable name for this facilitator",
    "required": false,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "FEE_BASIS_POINTS",
    "defaultValue": "10",
    "description": "Fee percentage in basis points (10 = 0.1%)",
    "required": false,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "FEE_PAYER_SECRET",
    "defaultValue": "your-fee-payer-secret-key-here",
    "description": "Base58-encoded secret key for facilitator wallet",
    "required": true,
    "source": "packages/facilitator/.env.alpha"
  },
  {
    "key": "STATS_RESET_PASSWORD",
    "defaultValue": "dev-reset-2024",
    "description": "Configuration variable",
    "required": false,
    "source": "packages/facilitator/.env.alpha"
  }
]

export const generatedAt = "2026-02-23T18:49:30.850Z"

// Helper function to get example by ID
export function getExample(id: string): CodeExample | undefined {
  return generatedCodeExamples.find(ex => ex.id === id)
}

// Helper function to get type by name
export function getType(name: string): TypeDefinition | undefined {
  return generatedTypeDefinitions.find(type => type.name === name)
}

// Helper function to get endpoint by path
export function getEndpoint(path: string, method?: string): APIEndpoint | undefined {
  return generatedAPIEndpoints.find(ep => 
    ep.path === path && (!method || ep.method === method)
  )
}
